export const adSelectors = [
  'div[class*="ad"]',
  'iframe[src*="ads"]',
  'ins.adsbygoogle',
  'div[id*="sponsored"]',
  'div[data-advertisement]',
  'section[data-testid="ad"]',
  'a[href*="doubleclick.net"]',
  'div[class*="sponsored"]',
  'div[data-ad-slot]',
  'div[class*="promoted"]',
  'aside[class*="ad"]',
  'div[class*="google_ads"]',
  'iframe[id*="google_ads"]',
  'iframe[src*="doubleclick"]',
  'div[class*="advertisement"]',
  'div[class*="ad-container"]',
  'div[class*="ad-slot"]',
  'div[class*="ad-banner"]',
];

export const filterFiles = [
  'filter_1.txt',
  'filter_2.txt',
  'filter_3.txt',
  'filter_4.txt',
  'filter_5.txt',
  'filter_6.txt',
  'filter_7.txt',
  'filter_8.txt',
];
